runtime: python27
api_version: 1
threadsafe: false
automatic_scaling:
  max_instances: 1

handlers:

- url: /favicon.ico
  static_files: www/favicon.ico
  upload: www/favicon.ico
  secure: always

- url: /(.*\.(gif|png|jpg))
  static_files: www/\1
  upload: www/(.*\.(gif|png|jpg))
  secure: always

- url: /.*
  script: index.app
  secure: always
